/* ============================================
   PARAIHSSANE — Product Data
   ============================================ */

const Products = [
  {
    id: 1,
    name: "Levure de bière Bio",
    price: 199,
    oldPrice: 249,
    category: "Compléments",
    image: "assets/images/products/levure-biere.svg",
    description: "Complément alimentaire à base de levure de bière, riche en vitamines B, minéraux et protéines. Contribue à la santé de la peau, des cheveux et des ongles.",
    featured: true,
    promotion: true,
    isNew: false,
    isBestSeller: true
  },
  {
    id: 2,
    name: "IMC Plus Beauté",
    price: 220,
    oldPrice: 260,
    category: "Compléments",
    image: "assets/images/products/imc-plus.svg",
    description: "Complément beauté pour un teint éclatant et une peau radieuse. Formule enrichie en vitamines et antioxydants.",
    featured: true,
    promotion: true,
    isNew: false,
    isBestSeller: true
  },
  {
    id: 3,
    name: "Rayonnelle Solaire SPF50",
    price: 179,
    oldPrice: null,
    category: "Solaire",
    image: "assets/images/products/rayonnelle-solaire.svg",
    description: "Crème solaire haute protection SPF50+ pour tous les types de peau. Protection UVA/UVB, résistante à l'eau.",
    featured: true,
    promotion: false,
    isNew: false,
    isBestSeller: true
  },
  {
    id: 4,
    name: "Sérum Éclat Vitamine C",
    price: 159,
    oldPrice: 199,
    category: "Visage",
    image: "assets/images/products/serum-vitamine-c.svg",
    description: "Sérum concentré en Vitamine C pour unifying et illuminer le teint. Réduit les taches sombres et stimule le collagène.",
    featured: true,
    promotion: true,
    isNew: true,
    isBestSeller: false
  },
  {
    id: 5,
    name: "Shampoing Kératine Anti-chute",
    price: 89,
    oldPrice: null,
    category: "Cheveux",
    image: "assets/images/products/shampoing-keratine.svg",
    description: "Shampoing enrichi en kératine pour renforcer les cheveux et lutter contre la chute. Convient à tous types de cheveux.",
    featured: true,
    promotion: false,
    isNew: false,
    isBestSeller: true
  },
  {
    id: 6,
    name: "Huile d'Argan Pure",
    price: 129,
    oldPrice: 159,
    category: "Beauté",
    image: "assets/images/products/huile-argan.svg",
    description: "Huile d'Argan du Maroc, 100% pure et naturelle. Pour le visage, les cheveux et le corps. Hydratation profonde.",
    featured: true,
    promotion: true,
    isNew: false,
    isBestSeller: true
  },
  {
    id: 7,
    name: "Crème Hydratante Corps",
    price: 99,
    oldPrice: null,
    category: "Corps",
    image: "assets/images/products/creme-hydratante.svg",
    description: "Crème hydratante pour le corps à la texture légère. Nourrit et protège la peau au quotidien.",
    featured: false,
    promotion: false,
    isNew: false,
    isBestSeller: false
  },
  {
    id: 8,
    name: "Pack Beauté Complet",
    price: 399,
    oldPrice: 520,
    category: "Packs",
    image: "assets/images/products/pack-beaute.svg",
    description: "Pack complet : Sérums, crème visage, huile d'argan et shampoing. La sélection idéale pour votre routine beauté.",
    featured: true,
    promotion: true,
    isNew: false,
    isBestSeller: true
  },
  {
    id: 9,
    name: "Masque Capillaire Karité",
    price: 79,
    oldPrice: null,
    category: "Cheveux",
    image: "assets/images/products/masque-karite.svg",
    description: "Masque nutritif au beurre de karité pour cheveux secs et abîmés. Réparation intensive et brillance.",
    featured: false,
    promotion: false,
    isNew: true,
    isBestSeller: false
  },
  {
    id: 10,
    name: "Gel Douche Aloe Vera",
    price: 49,
    oldPrice: null,
    category: "Hygiène",
    image: "assets/images/products/gel-aloe-vera.svg",
    description: "Gel douche doux à l'aloe vera pour une peau propre et hydratée. Formule sans paraben.",
    featured: false,
    promotion: false,
    isNew: false,
    isBestSeller: false
  },
  {
    id: 11,
    name: "Crème Contour des Yeux",
    price: 139,
    oldPrice: 169,
    category: "Visage",
    image: "assets/images/products/creme-yeux.svg",
    description: "Soin contour des yeux anti-cernes et anti-rides. Formule délicate pour la peau sensible de l'oeil.",
    featured: false,
    promotion: true,
    isNew: false,
    isBestSeller: false
  },
  {
    id: 12,
    name: "Pack Cheveux Réparation",
    price: 249,
    oldPrice: 310,
    category: "Packs",
    image: "assets/images/products/pack-cheveux.svg",
    description: "Pack complet pour cheveux : shampoing, masque et huile de ricin. Réparation et nutrition profonde.",
    featured: true,
    promotion: true,
    isNew: false,
    isBestSeller: false
  },
  {
    id: 13,
    name: "Eau Thermale Apaisante",
    price: 69,
    oldPrice: null,
    category: "Visage",
    image: "assets/images/products/eau-thermale.svg",
    description: "Eau thermale en brume pour apaiser et hydrater la peau. Idéale après le rasage ou l'exposition solaire.",
    featured: false,
    promotion: false,
    isNew: true,
    isBestSeller: false
  },
  {
    id: 14,
    name: "Beurre de Karite Pur",
    price: 89,
    oldPrice: null,
    category: "Corps",
    image: "assets/images/products/beurre-karite.svg",
    description: "Beurre de karité pur du Maroc. Hydratation intense pour le corps, les mains et les lèvres.",
    featured: false,
    promotion: false,
    isNew: false,
    isBestSeller: false
  },
  {
    id: 15,
    name: "Spray Volumineur Cheveux",
    price: 109,
    oldPrice: 139,
    category: "Cheveux",
    image: "assets/images/products/spray-volume.svg",
    description: "Spray volumineur pour cheveux fins. Donne du volume et de la texture sans alourdir.",
    featured: false,
    promotion: true,
    isNew: false,
    isBestSeller: false
  },
  {
    id: 16,
    name: "Nettoyant Moussant Visage",
    price: 59,
    oldPrice: null,
    category: "Visage",
    image: "assets/images/products/nettoyant-moussant.svg",
    description: "Nettoyant moussant doux pour le visage. Élimine les impuretés sans dessécher la peau.",
    featured: false,
    promotion: false,
    isNew: false,
    isBestSeller: false
  },
  {
    id: 17,
    name: "Protection Solaire Visage",
    price: 119,
    oldPrice: null,
    category: "Solaire",
    image: "assets/images/products/solaire-visage.svg",
    description: "Protection solaire légère pour le visage. SPF50, ne laisse pas de traces blanches.",
    featured: false,
    promotion: false,
    isNew: true,
    isBestSeller: false
  },
  {
    id: 18,
    name: "Pack Soin Corps Complet",
    price: 299,
    oldPrice: 380,
    category: "Packs",
    image: "assets/images/products/pack-corps.svg",
    description: "Pack soin du corps : gel douche, crème hydratante, beurre de karité et gommage.",
    featured: false,
    promotion: true,
    isNew: false,
    isBestSeller: false
  }
];
